### ISSUE TITLE
either this mod or terrablender is causing regular trees to decay leaves on spawn

### ISSUE THREAD

**Issue by TheGameKing1001** [rc-nunez-gonzalez/PinkExpansion#1]
I play with Fast Leaf Decay mod and for some reason either your mod or terrablender is causing all leaves to decay on regular trees when spawning in naturally, or when spawned via bonemeal. Not sure why tho.

Minecraft Version: 1.18.2
Forge Version: 1.18.2-forge-40.1.0
Mod version: PinkExpansion 0.8.0

**Comment by rc-nunez-gonzalez** [comment]
HI, sorry for the delay but this was a problems with datapacks, it's fixed since 0.9.0
